#!/usr/bin/env node

const minimist = require('minimist')
const colors = require('colors/safe')
const walk = require('../lib/walk')
const ui = require('../lib//ui')

const argv = minimist(process.argv.slice(2), {
  string: ['path'],
  boolean: ['help', 'remotes'],
  alias: {
    help: 'h',
    remotes: 'r',
    path: 'p'
  }
})

const help = () => {
  console.log(`
  ${colors.bold('turbostatus list')}

    List repos in current folder and show their status

  ${colors.dim('Options:')}

    -h, --help          output usage information
    -p, --path <path>   use <path> instead of current one

  ${colors.dim('Alias:')} ls
`)
}

if (argv.help) {
  help()
  process.exit(0)
}

ui.title()

if (argv.remotes) ui.infoRemotes()
walk(argv.path, argv.remotes).then(() => {
  ui.done()
}).catch((err) => { console.log(err) })

